feat: update to jina3
jina-ai/executor-vgg-audio-encoder pull request #6
Opened 2022-03-01 04:00 UTC by Hippopotamus0308

2022-03-01 05:59 UTC, nan-wang requested changes

2022-03-01 05:59 UTC, nan-wang commented on Dockerfile.gpu
> +RUN JINA_PIP_INSTALL_PERF=1 pip install --no-cache-dir jina~=3.0.3
```suggestion
RUN JINA_PIP_INSTALL_PERF=1 pip install --no-cache-dir jina~=3.0
```

2022-03-01 05:59 UTC, nan-wang commented on executor/vggish_audio_encoder.py
> +        traversal_paths: str = None,
```suggestion
        traversal_paths: str = '@r',
```

2022-03-01 05:59 UTC, nan-wang commented on executor/vggish_audio_encoder.py
> +        self.traversal_paths = traversal_paths or '@r'
```suggestion
        self.traversal_paths = traversal_paths
```

2022-03-01 05:59 UTC, nan-wang commented on executor/vggish_audio_encoder.py
> +            _mel_list = batch_docs.blobs
`blob` is renamed to `tensor`. https://docs.jina.ai/get-started/migrate/#common-errors-and-solutions
```suggestion
            _mel_list = batch_docs.tensors
```

2022-03-01 05:59 UTC, nan-wang commented on tests/unit/test_exec.py
> +        ['@cc, r', (('@r', 1), ('@c', 0), ('@cc', 2))],
```suggestion
        ['@cc,r', (('@r', 1), ('@c', 0), ('@cc', 2))],
```

2022-03-01 08:00 UTC, samsja approved these changes

2022-03-02 08:06 UTC, nan-wang approved these changes
LGTM👍

2022-03-02 08:06 UTC, merged